language: python
python:
  - "3.9"

install:
  - pip install pipenv codecov
  - pipenv sync --dev
  - cp contrib/env-sample .env

script:
  - flake8
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov