# Generated by Django 4.0.4 on 2022-05-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_modulo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
